// <auto-generated />
using System;
using AStarDev.OneDriveSyncClient.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStarDev.OneDriveSyncClient.Persistence.Migrations
{
    [DbContext(typeof(AStarDevContext))]
    partial class AStarDevContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AStarDev.OneDriveSyncClient.Persistence.SearchCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastKnownImageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastPageVisited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SearchConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SearchConfigurationId");

                    b.ToTable("SearchCategories", (string)null);
                });

            modelBuilder.Entity("AStarDev.OneDriveSyncClient.Persistence.SearchConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxImagePauseInMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchStringPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchStringSuffix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StartingPageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subscriptions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscriptionsStartingPageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubscriptionsTotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopWallpapers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TopWallpapersStartingPageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopWallpapersTotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseHeadless")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SearchConfigurations", (string)null);
                });

            modelBuilder.Entity("AStarDev.OneDriveSyncClient.Persistence.SearchCategory", b =>
                {
                    b.HasOne("AStarDev.OneDriveSyncClient.Persistence.SearchConfiguration", "SearchConfiguration")
                        .WithMany("SearchCategories")
                        .HasForeignKey("SearchConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchConfiguration");
                });

            modelBuilder.Entity("AStarDev.OneDriveSyncClient.Persistence.SearchConfiguration", b =>
                {
                    b.Navigation("SearchCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
