namespace AStar.Dev.Source.Generators;

/// <summary>
///     Provides a centralized location for constant values used in the AStar.Dev.Source.Generators library.
/// </summary>
public static partial class Constants
{
    /// <summary>
    ///     Represents a predefined string indicating the namespace of the source generators within the
    ///     AStar.Dev.Source.Generators library.
    /// </summary>
    public const string Namespace = "AStar.Dev.Source.Generators";

    /// <summary>
    ///     Represents a predefined string containing the header comment added to the top of generated source files,
    ///     indicating that the file is auto-generated by the AStar.Dev.Source.Generators library and should not be manually
    ///     edited.
    /// </summary>
    internal const string SourceGeneratorHeader = $"""
                                                   //----------------------
                                                   // <auto-generated>
                                                   //     Generated by {Namespace}
                                                   //     Do not edit this file manually. Any changes will be overwritten at the next build.
                                                   // </auto-generated>
                                                   //----------------------
                                                   """;

    internal const string GeneratedSourceXmlClassHeader = """
                                                          /// <summary>
                                                          /// Generated class header to quiet the compiler when XML Documentation is generated.
                                                          /// This class contains the registration for services tagged with the RegisterService attribute.
                                                          /// </summary>
                                                          """;

    internal const string GeneratedSourceXmlHeader = """
                                                     /// <summary>
                                                         /// Generated method summary to quiet the compiler when XML Documentation is generated.
                                                         /// </summary>
                                                     """;
}